// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: AppSecrets.firebaseWebApiKey,
    appId: AppSecrets.firebaseWebAppId,
    messagingSenderId: AppSecrets.firebaseWebMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    authDomain: AppSecrets.firebaseAuthDomain,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    measurementId: AppSecrets.firebaseWebMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppSecrets.firebaseAndroidApiKey,
    appId: AppSecrets.firebaseAndroidAppId,
    messagingSenderId: AppSecrets.firebaseWebMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: AppSecrets.firebaseIosApiKey,
    appId: AppSecrets.firebaseIosAppId,
    messagingSenderId: AppSecrets.firebaseWebMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    iosBundleId: AppSecrets.firebaseIosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: AppSecrets.firebaseIosApiKey,
    appId: AppSecrets.firebaseIosAppId,
    messagingSenderId: AppSecrets.firebaseWebMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    iosBundleId: AppSecrets.firebaseIosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: AppSecrets.firebaseWindowsApiKey,
    appId: AppSecrets.firebaseWindowsAppId,
    messagingSenderId: AppSecrets.firebaseWebMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    authDomain: AppSecrets.firebaseAuthDomain,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    measurementId: AppSecrets.firebaseWindowsMeasurementId,
  );
}
